### ISSUE TITLE
swap tests failing on master

### ISSUE THREAD

**Issue by gre** [LedgerHQ/ledger-live-common#900]
```

Summary of all failing tests
FAIL src/__tests__/cross.js (5.07 s)
  ● encode/decode swapHistory

    expect(received).toBe(expected) // Object.is equality

    Expected: 2
    Received: undefined

      59 |   const res = accountToAccountData(accountDataToAccount(data));
      60 |   expect(res).toMatchObject(data);
    > 61 |   expect(res.swapHistory?.length).toBe(2);
         |                                   ^
      62 | });
      63 | 
      64 | test("encode/decode swapHistory resilience", () => {

      at Object.<anonymous> (src/__tests__/cross.js:61:35)

  ● encode/decode swapHistory resilience

    expect(received).toBe(expected) // Object.is equality

    Expected: 0
    Received: undefined

      71 | 
      72 |   expect(res).toMatchObject(data);
    > 73 |   expect(res.swapHistory?.length).toBe(0);
         |                                   ^
      74 | });
      75 | 
      76 | test("encode/decode", () => {

      at Object.<anonymous> (src/__tests__/cross.js:73:35)

```

**Comment by juan-cortes** [comment]
https://github.com/LedgerHQ/ledger-live-common/pull/901
